import { MdContentCopy, MdOutlineModeEdit } from "react-icons/md";
const list = [
  {
    id: 1,
    s_no: 1,
    date: "5 / 06 / 2023",
    name: "Saral jain",
    zip: 454684,
    address: <MdContentCopy />,
    quantity: 1,
    amount: 200,
    payment_status: "Success",
    delivery_status: "Delivered",
    action: "Full_Detail",
  },
  {
    id: 2,
    s_no: 2,
    date: "7 / 05 / 2023",
    name: "Mohan",
    zip: 104684,
    address: <MdContentCopy />,
    quantity: 1,
    amount: 300,
    payment_status: "Success",
    delivery_status: "Rejected",
    action: "Full_Detail",
  },
  {
    id: 3,
    s_no: 3,
    date: "9 / 06 / 2023",
    name: "Suresh",
    zip: 454254,
    address: <MdContentCopy />,
    quantity: 1,
    amount: 200,
    payment_status: "Success",
    delivery_status: "Requested",
    action: "Full_Detail",
  },
  {
    id: 4,
    s_no: 4,
    date: "3 / 06 / 2023",
    name: "Pradeep",
    zip: 451284,
    address: <MdContentCopy />,
    quantity: 1,
    amount: 400,
    payment_status: "Success",
    delivery_status: "Delivered",
    action: "Full_Detail",
  },
  {
    id: 5,
    s_no: 5,
    date: "1 / 06 / 2023",
    name: "Gourav",
    zip: 984684,
    address: <MdContentCopy />,
    quantity: 1,
    amount: 100,
    payment_status: "Success",
    delivery_status: "Pending",
    action: "Full_Detail",
  },
  {
    id: 6,
    s_no: 6,
    date: "4 / 01 / 2023",
    name: "Deepak",
    zip: 454684,
    address: <MdContentCopy />,
    quantity: 1,
    amount: 350,
    payment_status: "Success",
    delivery_status: "Delivered",
    action: "Full_Detail",
  },
  {
    id: 7,
    s_no: 7,
    date: "2 / 06 / 2023",
    name: "Saral jain",
    zip: 634604,
    address: <MdContentCopy />,
    quantity: 1,
    amount: 240,
    payment_status: "Success",
    delivery_status: "Pending",
    action: "Full_Detail",
  },
  {
    id: 8,
    s_no: 8,
    date: "8 / 05 / 2023",
    name: "Rashail",
    zip: 454684,
    address: <MdContentCopy />,
    quantity: 1,
    amount: 200,
    payment_status: "Success",
    delivery_status: "Delivered",
    action: "Full_Detail",
  },
];

const list_2 = [
  {
    id: 1,
    s_no: 1,
    date: "5 / 06 / 2023",
    name: "Saral jain",
    number: 4546844544,
    subject: "Gsm Motor",
    status: "Pending",
    action: "Full_Detail",
  },
  {
    id: 2,
    s_no: 2,
    date: "7 / 05 / 2023",
    name: "Mohan",
    number: 1046841234,
    subject: "Gsm Motor",
    status: "Rejected",
    action: "Full_Detail",
  },
  {
    id: 3,
    s_no: 3,
    date: "9 / 06 / 2023",
    name: "Suresh",
    number: 1243454254,
    subject: "Gsm Motor",
    status: "Requested",
    action: "Full_Detail",
  },
  {
    id: 4,
    s_no: 4,
    date: "3 / 06 / 2023",
    name: "Pradeep",
    number: 4986551284,
    subject: "Gsm Motor",
    status: "Delivered",
    action: "Full_Detail",
  },
  {
    id: 5,
    s_no: 5,
    date: "1 / 06 / 2023",
    name: "Gourav",
    number: 9847845684,
    subject: "Gsm Motor",
    status: "Pending",
    action: "Full_Detail",
  },
  {
    id: 6,
    s_no: 6,
    date: "4 / 01 / 2023",
    name: "Deepak",
    number: 4546455468,
    subject: "Gsm Motor",
    status: "Delivered",
    action: "Full_Detail",
  },
  {
    id: 7,
    s_no: 7,
    date: "2 / 06 / 2023",
    name: "Saral jain",
    number: 6346014444,
    subject: "Gsm Motor",
    status: "Pending",
    action: "Full_Detail",
  },
  {
    id: 8,
    s_no: 8,
    date: "8 / 05 / 2023",
    name: "Rashail",
    number: 4547894684,
    subject: "Gsm Motor",
    status: "Delivered",
    action: "Full_Detail",
  },
];
const list_3 = [
  {
    id: 1,
    shn: "GSM-001",
    Product: "GSM Motor con...",
    category: "GSM Motor",
    availability: "Out Of Stock",
    stock: "10",
    mrp: "10999",
    discount: "10",
    price: "4930",
    edit: <MdOutlineModeEdit />,
  },
  {
    id: 2,
    shn: "GSM-001",
    Product: "GSM Motor con...",
    category: "GSM Motor",
    availability: "In Stock",
    stock: "20",
    mrp: "10999",
    discount: "10",
    price: "4930",
    edit: <MdOutlineModeEdit />,
  },
  {
    id: 3,
    shn: "GSM-021",
    Product: "GSM Motor con...",
    category: "GSM Motor",
    availability: "Out Of Stock",
    stock: "15",
    mrp: "10999",
    discount: "10",
    price: "5000",
    edit: <MdOutlineModeEdit />,
  },
  {
    id: 4,
    shn: "GSM-851",
    Product: "GSM Motor con...",
    category: "GSM Motor",
    availability: "In Stock",
    stock: "10",
    mrp: "10999",
    discount: "10",
    price: "7000",
    edit: <MdOutlineModeEdit />,
  },
  {
    id: 5,
    shn: "GSM-125",
    Product: "GSM Motor con...",
    category: "GSM Motor",
    availability: "Out Of Stock",
    stock: "30",
    mrp: "10999",
    discount: "10",
    price: "2930",
    edit: <MdOutlineModeEdit />,
  },
  {
    id: 6,
    shn: "GSM-081",
    Product: "GSM Motor con...",
    category: "GSM Motor",
    availability: "In Stock",
    stock: "10",
    mrp: "10999",
    discount: "10",
    price: "4930",
    edit: <MdOutlineModeEdit />,
  },
  {
    id: 7,
    shn: "GSM-301",
    Product: "GSM Motor con...",
    category: "GSM Motor",
    availability: "In Stock",
    stock: "10",
    mrp: "10999",
    discount: "10",
    price: "5630",
    edit: <MdOutlineModeEdit />,
  },
  {
    id: 8,
    shn: "GSM-211",
    Product: "GSM Motor con...",
    category: "GSM Motor",
    availability: "Out Of Stock",
    stock: "10",
    mrp: "10999",
    discount: "10",
    price: "6530",
    edit: <MdOutlineModeEdit />,
  },
];
export { list_2, list, list_3 };
